[package]
name = "soldoresol"
version = "0.1.0"
authors = ["soundrabbit <soundrabbitstd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = true
opt-level = 3

[dependencies]
js-sys = "0.3.36"
wasm-bindgen = "0.2.59"
serde = "1.0.105"
serde_derive = "1.0.105"
serde_json = "1.0.48"

[dependencies.kagura]
version = "0.8.4"

[dependencies.web-sys]
version = "0.3.32"
features = [
    "HtmlCanvasElement",
    "HtmlElement",
    "Node",
    "WebGlBuffer",
    "WebGlRenderingContext",
    "WebGlProgram",
    "WebGlShader",
]
